name: angel_generator
description: Code generators for using advanced Angel functionality without mirrors.
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/generator
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.0
  angel_serialize_generator: ^2.0.0
  build: ^1.0.0
  build_config: ^0.4.0
  code_builder: ^3.0.0
  source_gen: ^0.9.0
dev_dependencies:
  build_runner: ^1.0.0
  logging: ^0.11.0
  pedantic: ^1.0.0
  pretty_logging: ^1.0.0
  test: ^1.0.0
